bq_dbt:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('DBT_BIGQUERY_PROJECT') }}"
      dataset: "{{ env_var('DBT_BIGQUERY_DATASET') }}"
      threads: 2
      keyfile: "{{ env_var('DBT_BIGQUERY_KEYFILE') }}"
      location: "{{ env_var('DBT_BIGQUERY_LOCATION', 'US') }}"
      priority: interactive
